services:
  loki:
    image: cedricziel/dd-extension-lgtm-loki:dev
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol

  grafana:
    image: cedricziel/dd-extension-lgtm-grafana:dev
    container_name: dd-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=otelcol:4317
      - GF_TRACING_OPENTELEMETRY_OTLP_PROPAGATION=w3c
      - GF_FEATURE_TOGGLES_ENABLE=tempoBackendSearch,tempoSearch,tempoServiceGraph
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: cedricziel/dd-extension-lgtm-tempo:dev
    command: [ "-config.file=/etc/tempo.yaml" ]

  mimir:
    image: cedricziel/dd-extension-lgtm-mimir:dev
    container_name: dd-mimir
    restart: unless-stopped
    command: --config.file=/etc/mimir/demo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: cedricziel/dd-extension-lgtm-otelcol:dev
    container_name: dd-otelcol
    restart: unless-stopped
    ports:
      - "14268:14268"  # jaeger ingest
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
